"""Parser for roadmap files generated by the `sales-roadmap` skill.

Prefers the Markdown sidecar (same basename as the PDF) because it is robust to
parse. When only the PDF is available, falls back to text extraction with
PyMuPDF and parses the same sections.

Returns a dict with:
    {
        "project": str,
        "start_date": str,
        "end_date": str,
        "duration_working_days": int,
        "total_hours": float,
        "hours_by_role": {role: hours},   # normalized to canonical English names
        "phases": [{phase, start, end, hours}],
        "source_file": str,
    }
"""
from __future__ import annotations

import re
from pathlib import Path

# Role name normalization (roadmap names → canonical budget roles).
# Anything not listed is passed through unchanged.
ROLE_MAP = {
    "Backend": "Backend",
    "Frontend": "Frontend",
    "Arquitectura": "Architecture",
    "Architecture": "Architecture",
    "Diseño": "Design",
    "Design": "Design",
    "Discovery": "Product Owner",
    "Product Owner": "Product Owner",
    "Project Management": "Project Management",
    "PM": "Project Management",
}

CANONICAL_ROLES = [
    "Backend",
    "Frontend",
    "Architecture",
    "Design",
    "Project Management",
    "Product Owner",
]


def normalize_role(name: str) -> str:
    return ROLE_MAP.get(name.strip(), name.strip())


def _read_text(file_path: Path) -> str:
    if file_path.suffix.lower() == ".md":
        return file_path.read_text(encoding="utf-8")
    if file_path.suffix.lower() == ".pdf":
        import fitz  # PyMuPDF, installed as a dependency of markdown-pdf
        doc = fitz.open(str(file_path))
        chunks = [page.get_text("text") for page in doc]
        doc.close()
        return "\n".join(chunks)
    raise ValueError(f"Unsupported file format: {file_path.suffix}")


def _parse_title(text: str) -> str:
    m = re.search(r"^#\s*Roadmap[\s—\-]+(.+?)$", text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    m = re.search(r"Roadmap[\s—\-]+(.+)", text)
    return m.group(1).strip() if m else ""


def _parse_summary(text: str) -> dict:
    out = {
        "start_date": "",
        "end_date": "",
        "duration_working_days": 0,
        "total_hours": 0.0,
    }
    # Roadmap labels are in Spanish ("Fecha de inicio efectiva", "Horas totales", etc.)
    m = re.search(r"Fecha de inicio efectiva[^0-9]*([\d\-]+)", text)
    if m:
        out["start_date"] = m.group(1)
    m = re.search(r"Fecha estimada de fin[^0-9]*([\d\-]+)", text)
    if m:
        out["end_date"] = m.group(1)
    m = re.search(r"Duraci[oó]n[^0-9]*(\d+)\s*d[ií]as laborales", text)
    if m:
        out["duration_working_days"] = int(m.group(1))
    m = re.search(r"Horas totales[^0-9]*([\d\.,]+)", text)
    if m:
        out["total_hours"] = float(m.group(1).replace(",", "."))
    return out


def _parse_hours_by_dept(text: str) -> dict[str, float]:
    """Extracts the first table following the hours-per-area/department heading.
    Accepts both legacy ('Horas por departamento') and current ('Horas por área')
    roadmap headings. Works for both MD content and PDF-extracted text."""
    result: dict[str, float] = {}
    in_section = False
    table_started = False
    for line in text.splitlines():
        stripped = line.strip()
        if re.match(r"^##\s*Horas por (departamento|[aá]rea)", stripped):
            in_section = True
            continue
        if not in_section:
            continue
        if stripped.startswith("##"):
            break
        if stripped.startswith("|"):
            table_started = True
            if "---" in stripped or re.match(r"^\|\s*(Departamento|[ÁA]rea|Role|Rol)\s*\|", stripped):
                continue
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            if len(cells) >= 2:
                try:
                    result[cells[0]] = float(cells[1].replace(",", "."))
                except ValueError:
                    continue
        elif table_started and not stripped:
            break
    return result


def _parse_phases(text: str) -> list[dict]:
    """Extracts the phases table rows into {phase, start, end, hours}.
    Accepts both 'Fases' and 'Fases del proyecto' headings."""
    result: list[dict] = []
    in_section = False
    table_started = False
    for line in text.splitlines():
        stripped = line.strip()
        if re.match(r"^##\s*Fases\b", stripped):
            in_section = True
            continue
        if not in_section:
            continue
        if stripped.startswith("##"):
            break
        if stripped.startswith("|"):
            table_started = True
            if "---" in stripped or "Fase" in stripped:
                continue
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            if len(cells) >= 4:
                try:
                    result.append(
                        {
                            "phase": cells[0],
                            "start": cells[1],
                            "end": cells[2],
                            "hours": float(cells[3].replace(",", ".")),
                        }
                    )
                except ValueError:
                    continue
        elif table_started and not stripped:
            break
    return result


def parse_roadmap(file_path: Path) -> dict:
    text = _read_text(file_path)

    raw_hours = _parse_hours_by_dept(text)
    hours_by_role: dict[str, float] = {}
    for raw_name, hrs in raw_hours.items():
        norm = normalize_role(raw_name)
        hours_by_role[norm] = hours_by_role.get(norm, 0.0) + hrs

    summary = _parse_summary(text)
    if summary["total_hours"] == 0.0 and hours_by_role:
        summary["total_hours"] = round(sum(hours_by_role.values()), 2)

    return {
        "project": _parse_title(text),
        **summary,
        "hours_by_role": hours_by_role,
        "phases": _parse_phases(text),
        "source_file": str(file_path),
    }
