import { MOCK_LEADS } from "@/lib/mock-data"
import { notFound } from "next/navigation"
import { Star, Globe, ArrowRight } from "lucide-react"

interface Props {
  params: Promise<{ leadId: string }>
}

export default async function ClientViewPage({ params }: Props) {
  const { leadId } = await params
  const lead = MOCK_LEADS.find((l) => l.id === leadId)

  if (!lead) notFound()

  return (
    <div className="min-h-screen bg-white flex flex-col">
      {/* Minimal header */}
      <header className="border-b border-gray-100 px-6 py-4 flex items-center justify-between">
        <div className="text-sm font-semibold text-gray-900">
          Proposal from <span className="text-indigo-600">Folio Agency</span>
        </div>
        <div className="text-xs text-gray-400">
          {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
        </div>
      </header>

      <main className="flex-1 max-w-4xl mx-auto w-full px-6 py-10 space-y-8">
        {/* Hero */}
        <div className="rounded-2xl bg-gradient-to-br from-indigo-50 to-white border border-indigo-100 p-8">
          <div className="text-xs text-indigo-500 font-semibold uppercase tracking-wider mb-2">
            Website Proposal
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">{lead.name}</h1>
          <div className="flex items-center gap-4 text-sm text-gray-500">
            <span>{lead.industry}</span>
            <span>·</span>
            <span className="flex items-center gap-1">
              <Globe size={13} />
              {lead.location}
            </span>
            {lead.socialPresence.googleMapsRating ? (
              <>
                <span>·</span>
                <span className="flex items-center gap-1">
                  <Star size={12} className="fill-amber-400 text-amber-400" />
                  {lead.socialPresence.googleMapsRating} ({lead.socialPresence.googleMapsReviews} reviews)
                </span>
              </>
            ) : null}
          </div>
        </div>

        {/* Site preview */}
        {lead.previewUrl ? (
          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Your new website</h2>
            <div className="rounded-2xl border border-gray-200 overflow-hidden shadow-sm">
              <div className="bg-gray-50 border-b border-gray-200 px-4 py-3 flex items-center gap-3">
                <div className="flex gap-1.5">
                  <div className="w-3 h-3 rounded-full bg-red-400/60" />
                  <div className="w-3 h-3 rounded-full bg-yellow-400/60" />
                  <div className="w-3 h-3 rounded-full bg-green-400/60" />
                </div>
                <div className="flex-1 bg-white rounded-md px-3 py-1 text-xs text-gray-400 border border-gray-200">
                  {lead.name.toLowerCase().replace(/\s+/g, "")}.com.ar
                </div>
              </div>
              <iframe
                src={lead.previewUrl}
                title={`New website for ${lead.name}`}
                className="w-full h-[520px] border-0"
                sandbox="allow-scripts allow-same-origin"
              />
            </div>
            <a
              href={lead.previewUrl}
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center gap-1.5 text-sm text-indigo-600 hover:text-indigo-700 mt-3"
            >
              Open full preview
              <ArrowRight size={13} />
            </a>
          </div>
        ) : null}

        {/* Proposal */}
        {lead.proposalHtml ? (
          <div className="rounded-2xl border border-gray-200 p-8">
            <div
              dangerouslySetInnerHTML={{ __html: lead.proposalHtml }}
            />
          </div>
        ) : null}

        {/* CTA */}
        <div className="rounded-2xl bg-indigo-600 text-white p-8 text-center">
          <h2 className="text-2xl font-bold mb-2">Ready to move forward?</h2>
          <p className="text-indigo-200 mb-6 text-sm">
            Reply to our email or use the button below to schedule a 20-minute call.
          </p>
          <a
            href="https://wa.me/5491100000000"
            className="inline-block bg-white text-indigo-600 font-bold px-8 py-3 rounded-xl text-sm hover:bg-indigo-50 transition-colors"
          >
            Let&apos;s talk →
          </a>
        </div>
      </main>

      <footer className="border-t border-gray-100 text-center py-4 text-xs text-gray-400">
        Proposal generated by Folio · {new Date().getFullYear()}
      </footer>
    </div>
  )
}
